SET TERM ^ ;

create or alter procedure CADASTRAR_REQUISICAO_ITENS (
    DESCRICAO       VARCHAR(60),
    ID_ITEM         INTEGER NOT NULL)
as
declare variable CD_REQ integer;
BEGIN
    
    SELECT MAX(ID_REQUISICAO) FROM REQUISICOES INTO :CD_REQ;
    
    INSERT INTO REQUISICOES_ITENS (ID_REQUISICAO, ID_ITEM, ID_PRODUTO, DESCRICAO, QTDE, VALOR_UNITARIO, REF, DADOS, CODIGO_FAB, MARCA, CODIGO_BARRA, ENTREGAR, ENTREGUE, DATA_ENTREGA)
                       VALUES (:CD_REQ, :ID_ITEM, NULL, :DESCRICAO, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

END^

SET TERM ; ^


