SET TERM ^ ;

CREATE OR ALTER PROCEDURE GERAR_REQUISICAO (
    CODCLIENTE         VARCHAR(8),
    PEDIDO             VARCHAR(18),
    NPEDIDOGMSAP       VARCHAR(8),
    PECA VARCHAR(30),
    QTD  INTEGER NOT NULL)
AS
DECLARE VARIABLE CD_REQ INTEGER;
DECLARE VARIABLE DATA_HOJE DATE;
DECLARE VARIABLE HORA_HOJE TIME;
DECLARE VARIABLE dataAtual TIMESTAMP;
DECLARE VARIABLE ID_CLIENTE_REQ INTEGER;
DECLARE VARIABLE ID_PRODUTO NUMERIC;
DECLARE VARIABLE DESCRICAO VARCHAR(190);
DECLARE VARIABLE ID_ITEM INTEGER;
DECLARE VALOR_UNITARIO  CURRENCY;
DECLARE REF             VARCHAR(15);
DECLARE CODIGO_FAB      VARCHAR(20);
DECLARE MARCA           VARCHAR(50);
DECLARE CODIGO_BARRA    VARCHAR(40);
BEGIN
    dataAtual = CURRENT_TIMESTAMP;
    DATA_HOJE = CURRENT_DATE;
    HORA_HOJE = CURRENT_TIME;
    SELECT MAX(ID_ITEM) FROM REQUISICOES_ITENS INTO :ID_ITEM;
    ID_ITEM = COALESCE(ID_ITEM, 0) + 1;


    SELECT ID_PRODUTO FROM produtos p WHERE p.codigo_fab = :PECA ORDER BY descricao rows 1 INTO :ID_PRODUTO;
    SELECT DESCRICAO FROM produtos p WHERE p.codigo_fab = :PECA ORDER BY descricao rows 1 INTO :DESCRICAO;
    SELECT PRECO_TABELA FROM PRODUTO_PRECOS p WHERE p.ID_PRODUTO = :ID_PRODUTO INTO :VALOR_UNITARIO;
    SELECT REF FROM produtos p WHERE p.codigo_fab = :PECA ORDER BY descricao rows 1 INTO :REF;
    SELECT CODIGO_FAB FROM produtos p WHERE p.codigo_fab = :PECA ORDER BY descricao rows 1 INTO :CODIGO_FAB;
    SELECT MARCA FROM produtos p WHERE p.codigo_fab = :PECA ORDER BY descricao rows 1 INTO :MARCA;
    SELECT CODIGO_BARRA FROM produtos p WHERE p.codigo_fab = :PECA ORDER BY descricao rows 1 INTO :CODIGO_BARRA;
    SELECT ID_CLIENTE FROM CLIENTES c where c.DOC_EX = :CODCLIENTE INTO :ID_CLIENTE_REQ;
    SELECT MAX(ID_REQUISICAO) FROM REQUISICOES INTO :CD_REQ;
    CD_REQ = COALESCE(CD_REQ, 0) + 1;

    INSERT INTO REQUISICOES (
        ID_REQUISICAO,
        ES,
        ID_CLIENTE,
        DATA_EMISSAO,
        HORA_EMISSAO,
        NUMERO,
        ID_FUNCIONARIO,
        PEDIDO,
        OBS,
        VALOR_REQUISICAO,
        ID_VEICULO,
        ID_DEPTO,
        COTACAO,
        STATUS,
        VEICULO,
        PLACA,
        ITENS,
        ENTREGUE
    ) VALUES (
        :CD_REQ,
        1,
        :ID_CLIENTE_REQ,
        :DATA_HOJE,
        :HORA_HOJE,
        NULL,
        NULL,
        :PEDIDO,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        :NPEDIDOGMSAP,
        NULL,
        NULL
    );

    INSERT INTO REQUISICOES_ITENS (
        ID_REQUISICAO, 
        ID_ITEM, 
        ID_PRODUTO, 
        DESCRICAO, 
        QTDE, 
        VALOR_UNITARIO, 
        REF, 
        DADOS, 
        CODIGO_FAB, 
        MARCA, 
        CODIGO_BARRA, 
        ENTREGAR, 
        ENTREGUE, 
        DATA_ENTREGA
    ) 
    VALUES (
        :CD_REQ, 
        :ID_ITEM, 
        :ID_PRODUTO, 
        :DESCRICAO, 
        :QTD, 
        :VALOR_UNITARIO, 
        :REF, 
        NULL, 
        :CODIGO_FAB, 
        :MARCA, 
        :CODIGO_BARRA, 
        :QTD, 
        0, 
        NULL
    );

END^

SET TERM ; ^
