SET TERM ^ ;

create or alter procedure CADASTRAR_REQUISICAO (
    OBS               BLOB SUB_TYPE 1 SEGMENT SIZE 80

    )
as
declare variable CD_REQ integer;
declare variable DATA_HOJE DATE;
declare variable HORA_HOJE DATE;
BEGIN
    
    SELECT MAX(ID_REQUISICAO) FROM REQUISICOES INTO :CD_REQ;
    CD_REQ = (CD_REQ+1);
    DATA_HOJE = CURRENT_DATE();
    HORA_HOJE = CURRENT_TIME();

    INSERT INTO REQUISICOES (ID_REQUISICAO, ES, ID_CLIENTE, DATA_EMISSAO, HORA_EMISSAO, NUMERO, ID_FUNCIONARIO, PEDIDO, OBS, VALOR_REQUISICAO, ID_VEICULO, ID_DEPTO, COTACAO, STATUS, VEICULO, PLACA, ITENS, ENTREGUE)
                 VALUES (:CD_REQ, NULL, NULL, :DATA_HOJE, :HORA_HOJE, NULL, NULL, NULL, :OBS, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

END^

SET TERM ; ^

