SET TERM ^ ;

create or alter procedure MOB_CADASTRAR_PEDIDO_ITEM (
    ID_PEDIDO integer,
    PRODUTO integer,
    QUANTIDADE float,
    OBSERVACAO varchar(80),
    VALOR_UNITARIO MOEDA,
    VALOR_DESCONTO MOEDA,
    VALOR_TOTAL MOEDA)
as
declare variable ITEM integer;
BEGIN

    SELECT COALESCE(MAX(ID_ITEM),0)+1 FROM PEDIDO_ITENS WHERE ID_PEDIDO = :ID_PEDIDO INTO :ITEM;

    INSERT INTO PEDIDO_ITENS (ID_PEDIDO, ID_ITEM, ID_PRODUTO, DESCRICAO, UNIDADE, QTDE, VALOR_UNITARIO, CF, VALOR_TOTAL, VALOR_FINAL, VALOR_FINAL_UN,
           TIPO, VALOR_CUSTO, CODIGO_BARRA, TIPO_UNIDADE, DESCONTO, STATUS, ICMS, REDUCAO_ICMS, TRIBUTACAO,
           BASE_CALCULO, VALOR_ICMS, BASE_ICMS_SUB, VALOR_ICMS_SUB, PESO, CFOP, PIS_CST, COFINS_CST, IPI_CST, PIS, COFINS, IPI, CSOSN,
           ORIGEM, LUCRO, LUCRO_MAX, ENTREGAR, VALOR_IPI, BASE_IPI, BASE_PIS, BASE_COFINS)
           VALUES ( :ID_PEDIDO, :ITEM, :PRODUTO,
           (SELECT DESCRICAO FROM PRODUTOS WHERE ID_PRODUTO = :PRODUTO),
           (SELECT UNIDADE FROM PRODUTOS WHERE ID_PRODUTO = :PRODUTO),
           :QUANTIDADE, :VALOR_UNITARIO,
           (SELECT ORIGEM_MERCADORIA || TRIBUTACAO FROM PRODUTOS WHERE ID_PRODUTO = :PRODUTO),
           (:VALOR_TOTAL+:VALOR_DESCONTO), :VALOR_TOTAL, :VALOR_UNITARIO, 1,
                              (SELECT PRODUTO_PRECOS.PRECO_CUSTO FROM PRODUTOS, PRODUTO_PRECOS WHERE (PRODUTOS.ID_PRODUTO = PRODUTO_PRECOS.ID_PRODUTO) AND (PRODUTO_PRECOS.ATIVO = 1) AND (PRODUTOS.ID_PRODUTO = :PRODUTO)),
                              (SELECT CODIGO_BARRA FROM PRODUTOS WHERE ID_PRODUTO = :PRODUTO), 1,
                              ((:VALOR_DESCONTO*100)/(:VALOR_TOTAL+:VALOR_DESCONTO)), 1,
                              (SELECT ICMS FROM PRODUTOS WHERE ID_PRODUTO = :PRODUTO),
                              (SELECT REDUCAO FROM PRODUTOS WHERE ID_PRODUTO = :PRODUTO),
                              (SELECT TRIBUTACAO FROM PRODUTOS WHERE ID_PRODUTO = :PRODUTO),
                              0,
                              0,
                              0,
                              0,
                              (SELECT PESO FROM PRODUTOS WHERE ID_PRODUTO = :PRODUTO), (SELECT CFOP_E FROM PRODUTOS WHERE ID_PRODUTO = :PRODUTO),
                              (SELECT PIS_CST FROM PRODUTOS WHERE ID_PRODUTO = :PRODUTO),
                              (SELECT COFINS_CST FROM PRODUTOS WHERE ID_PRODUTO = :PRODUTO),
                              (SELECT IPI_CST FROM PRODUTOS WHERE ID_PRODUTO = :PRODUTO),
                              (SELECT PIS FROM PRODUTOS WHERE ID_PRODUTO = :PRODUTO),
                              (SELECT COFINS FROM PRODUTOS WHERE ID_PRODUTO = :PRODUTO),
                              (SELECT IPI FROM PRODUTOS WHERE ID_PRODUTO = :PRODUTO),
                              (SELECT CSOSN FROM PRODUTOS WHERE ID_PRODUTO = :PRODUTO),
                              (SELECT ORIGEM_MERCADORIA FROM PRODUTOS WHERE ID_PRODUTO = :PRODUTO),
                              (SELECT MARGEM_LUCRO FROM PRODUTOS WHERE ID_PRODUTO = :PRODUTO),
                              (SELECT MARGEM_MAXIMA FROM PRODUTOS WHERE ID_PRODUTO = :PRODUTO), 0,
                              0,
                              0,
                              0,
                              0);


    UPDATE PEDIDOS SET
    PESO_TOTAL = (SELECT SUM(PESO) FROM PEDIDO_ITENS WHERE ID_PEDIDO = :ID_PEDIDO)
    WHERE ID_PEDIDO = :ID_PEDIDO;

END^

SET TERM ; ^

/* Following GRANT statetements are generated automatically */

GRANT SELECT,INSERT ON PEDIDO_ITENS TO PROCEDURE MOB_CADASTRAR_PEDIDO_ITEM;
GRANT SELECT ON PRODUTOS TO PROCEDURE MOB_CADASTRAR_PEDIDO_ITEM;
GRANT SELECT ON PRODUTO_PRECOS TO PROCEDURE MOB_CADASTRAR_PEDIDO_ITEM;
GRANT SELECT,UPDATE ON PEDIDOS TO PROCEDURE MOB_CADASTRAR_PEDIDO_ITEM;

/* Existing privileges on this procedure */

GRANT EXECUTE ON PROCEDURE MOB_CADASTRAR_PEDIDO_ITEM TO SYSDBA;