/******************************************************************************/
/***               Generated by IBExpert 14/04/2023 15:05:40                ***/
/******************************************************************************/

/******************************************************************************/
/***      Following SET SQL DIALECT is just for the Database Comparer       ***/
/******************************************************************************/
SET SQL DIALECT 3;



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/



CREATE TABLE PEDIDOS (
    ID_PEDIDO             NUMERIC(9,0) NOT NULL,
    ID_ESPECIE            INTEGER,
    ID_FORMA              INTEGER,
    ID_VENDEDOR           INTEGER,
    ID_FUNCIONARIO        INTEGER,
    DATA_HORA             TIMESTAMP,
    ID_NATUREZA           INTEGER,
    DATA_VENCIMENTO       DATE,
    ID_CLIENTE            NUMERIC(9,0),
    VALOR_ENTRADA         MOEDA /* MOEDA = DECIMAL(15,2) */,
    DESCONTO              FLOAT,
    VALOR_PEDIDO          MOEDA /* MOEDA = DECIMAL(15,2) */,
    VALOR_FRETE           MOEDA /* MOEDA = DECIMAL(15,2) */,
    NF                    SMALLINT,
    NOTA_FISCAL           VARCHAR(18),
    ID_DEPTO              INTEGER,
    STATUS                SMALLINT,
    BASE_CALCULO          MOEDA /* MOEDA = DECIMAL(15,2) */,
    VALOR_ICMS            MOEDA /* MOEDA = DECIMAL(15,2) */,
    PEDIDO                VARCHAR(18),
    OBS                   BLOB SUB_TYPE 0 SEGMENT SIZE 80,
    TIPO                  SMALLINT,
    ID_REFERENCIA         INTEGER,
    ITENS                 INTEGER,
    PLACA_VEICULO         VARCHAR(8),
    VEICULO               VARCHAR(20),
    VALOR_IPI             MOEDA /* MOEDA = DECIMAL(15,2) */,
    OUTRAS_DESPESAS       MOEDA /* MOEDA = DECIMAL(15,2) */,
    COMISSAO              FLOAT,
    PESO_TOTAL            FLOAT,
    N_NOTA                SMALLINT,
    ID_VEICULO            INTEGER,
    KM_VEICULO            INTEGER,
    MOTORISTA             VARCHAR(50),
    VALOR_SERVICOS        MOEDA /* MOEDA = DECIMAL(15,2) */,
    SELECIONA             SMALLINT,
    VALOR_CUSTOS          MOEDA /* MOEDA = DECIMAL(15,2) */,
    ID_PROPRIEDADE        INTEGER,
    MARCADOR              SMALLINT,
    DADOS                 BLOB SUB_TYPE 1 SEGMENT SIZE 80,
    NUMERO                INTEGER,
    SERVICOS              INTEGER,
    ID_CAIXA              INTEGER,
    TIPO_PO               SMALLINT,
    VALOR_RECEBIDO        DECIMAL(15,2),
    QTDE_TOTAL            INTEGER,
    AJUSTE                DECIMAL(15,2),
    BASE_ICMS_SUB         MOEDA /* MOEDA = DECIMAL(15,2) */,
    VALOR_ICMS_SUB        MOEDA /* MOEDA = DECIMAL(15,2) */,
    VALOR_ICMS_PREV       MOEDA /* MOEDA = DECIMAL(15,2) */,
    TIPO_NOTA             SMALLINT,
    TIPO_FRETE            SMALLINT,
    ID_PORTADOR           INTEGER,
    TIPO_A_PRECO          SMALLINT,
    ID_LENTE              INTEGER,
    ACRESCIMO             FLOAT,
    ISS                   FLOAT,
    ID_TABELA             INTEGER,
    ID_MOV_CAIXA          INTEGER,
    OPE_ICMS_CUSTO        SMALLINT,
    OPE_DESCONTO          SMALLINT,
    OPE_FRETE_ICMS        SMALLINT,
    DEVOLUCAO             SMALLINT,
    SERIE                 VARCHAR(3),
    ENTREGA               SMALLINT,
    OPE_CALC_SUBST        SMALLINT,
    OPE_CALC_FRETE        SMALLINT,
    CUPOM_FISCAL          VARCHAR(18),
    VALOR_BASE            MOEDA /* MOEDA = DECIMAL(15,2) */,
    OPE_DET_PARC          SMALLINT,
    DATA_ENTREGA          DATE,
    NOTA_FISCAL_SERV      VARCHAR(18),
    PRAZO                 INTEGER,
    DATA_VALIDADE         DATE,
    FRETE_TON             MOEDA /* MOEDA = DECIMAL(15,2) */,
    ID_TRANSPORTADORA     INTEGER,
    TIPO_TRANSPORTE       SMALLINT,
    CARTAO                INTEGER,
    ID_MOBILE             INTEGER,
    DATA_AF               TIMESTAMP,
    ID_ENTREGA            INTEGER,
    ID_REFERENCIA2        INTEGER,
    NPV                   INTEGER,
    DAV                   INTEGER,
    ID_PDV                INTEGER,
    ID_ECF                INTEGER,
    TIPO_DP               SMALLINT,
    TIPO_DAV              SMALLINT,
    TIPO_DESCONTO         SMALLINT,
    ID_USUARIO            INTEGER,
    NFP                   VARCHAR(18),
    TIPO_ENTREGA          SMALLINT,
    EMAIL_ENVIADO         SMALLINT,
    OPE_ICMS_DESCONTO     SMALLINT,
    FUNRURAL              FLOAT,
    DESCRICAO             VARCHAR(70),
    ID_DEPTO_DESTINO      INTEGER,
    IRRF                  FLOAT,
    VALOR_TRIBUTADO       MOEDA /* MOEDA = DECIMAL(15,2) */,
    VALOR_SUBSTITUTO      MOEDA /* MOEDA = DECIMAL(15,2) */,
    ID_OSF                INTEGER,
    DATA_REAJUSTE         DATE,
    CHAVE_NFE             VARCHAR(80),
    OPE_IPI_FRETE         SMALLINT,
    OPE_DESCONTO_BASE     SMALLINT,
    OPE_IPI_BASE          SMALLINT,
    OPE_CREDITO_ICMS      SMALLINT,
    TIPO_EMISSAO          SMALLINT,
    VALOR_PIS             MOEDA /* MOEDA = DECIMAL(15,2) */,
    VALOR_COFINS          MOEDA /* MOEDA = DECIMAL(15,2) */,
    ID_ECF_EMISSAO        INTEGER,
    ID_CUPOM              INTEGER,
    COO                   VARCHAR(6),
    CCF                   VARCHAR(6),
    CODE                  VARCHAR(32),
    ID_PEDIDO_ORIGEM      INTEGER,
    LOCALIZADOR           VARCHAR(20),
    CONDICIONAL           SMALLINT,
    ID_NATUREZA_DESTINO   INTEGER,
    AJUSTE_DESCONTO       SMALLINT,
    ID_EQUIPAMENTO        INTEGER,
    ID_ENDERECO           INTEGER,
    KM_FINAL              INTEGER,
    OPE_BASE_ICMS_CA      SMALLINT,
    CONTROLE_FP           SMALLINT,
    OBS2                  BLOB SUB_TYPE 1 SEGMENT SIZE 80,
    STATUS_ENTREGA        SMALLINT,
    SEPARA                SMALLINT,
    VINCULADO             VARCHAR(20),
    NFCE_NUMERO           VARCHAR(18),
    IDENTIFICADOR         VARCHAR(20),
    ID_NOTA               INTEGER,
    OPE_OD_BASE           SMALLINT,
    VALOR_ICMS_GAR        MOEDA /* MOEDA = DECIMAL(15,2) */,
    VALOR_GARANTIDO       MOEDA /* MOEDA = DECIMAL(15,2) */,
    OPE_CUSTO_SEL         SMALLINT,
    VALOR_MARCADO2        MOEDA /* MOEDA = DECIMAL(15,2) */,
    RECALCULAR            SMALLINT,
    OPE_MARGEM_CUSTO      SMALLINT,
    NFCE_NSU              VARCHAR(15),
    ID_NF_IG              INTEGER,
    ID_NFCE               INTEGER,
    VALOR_FCPST           MOEDA /* MOEDA = DECIMAL(15,2) */,
    ID_STATUS             INTEGER,
    VALOR_DESCONTO        MOEDA /* MOEDA = DECIMAL(15,2) */,
    VALOR_ACRESCIMO       MOEDA /* MOEDA = DECIMAL(15,2) */,
    OPE_SOMA_OD           SMALLINT,
    DATA_FINAL            DATE,
    ID_REQUISICAO         INTEGER,
    VALOR_CREDITO         MOEDA /* MOEDA = DECIMAL(15,2) */,
    ID_COMANDA            INTEGER,
    COMANDA               VARCHAR(40),
    OPD_TERCEIROS         SMALLINT,
    DATA_HORA_AGENDA      TIMESTAMP,
    OPS_MVA_ZERO          SMALLINT,
    DIAS_ENTRADA          SMALLINT,
    OPE_IPI_OD            SMALLINT,
    DESCONTOSV            FLOAT,
    DATA_CANCEL           TIMESTAMP,
    STATUSWEB             SMALLINT,
    VALOR_CRED_SN         MOEDA /* MOEDA = DECIMAL(15,2) */,
    VALOR_MINIMOS         MOEDA /* MOEDA = DECIMAL(15,2) */,
    OPE_IPI_DESCONTO      SMALLINT,
    OPE_ZERA_BC           SMALLINT,
    VALOR_ICMS_DESON      MOEDA /* MOEDA = DECIMAL(15,2) */,
    OPE_DESON_DESCONTO    SMALLINT,
    OPE_DESON_DESC_CUSTO  SMALLINT,
    OPS_IND_FINAL         SMALLINT
);




/******************************************************************************/
/***                              Primary Keys                              ***/
/******************************************************************************/

ALTER TABLE PEDIDOS ADD PRIMARY KEY (ID_PEDIDO);


/******************************************************************************/
/***                                Indices                                 ***/
/******************************************************************************/

CREATE INDEX PEDIDOS_IDX1 ON PEDIDOS (ID_CLIENTE);
CREATE INDEX PEDIDOS_IDX10 ON PEDIDOS (ID_PEDIDO_ORIGEM);
CREATE INDEX PEDIDOS_IDX11 ON PEDIDOS (ID_CUPOM);
CREATE INDEX PEDIDOS_IDX12 ON PEDIDOS (CUPOM_FISCAL);
CREATE INDEX PEDIDOS_IDX13 ON PEDIDOS (TIPO);
CREATE INDEX PEDIDOS_IDX14 ON PEDIDOS (ID_DEPTO);
CREATE INDEX PEDIDOS_IDX15 ON PEDIDOS (STATUS);
CREATE INDEX PEDIDOS_IDX16 ON PEDIDOS (DATA_VENCIMENTO);
CREATE INDEX PEDIDOS_IDX17 ON PEDIDOS (ID_LENTE);
CREATE INDEX PEDIDOS_IDX18 ON PEDIDOS (ID_REQUISICAO);
CREATE INDEX PEDIDOS_IDX19 ON PEDIDOS (ID_ENDERECO);
CREATE INDEX PEDIDOS_IDX2 ON PEDIDOS (ID_NATUREZA);
CREATE INDEX PEDIDOS_IDX3 ON PEDIDOS (DATA_HORA);
CREATE INDEX PEDIDOS_IDX4 ON PEDIDOS (ID_ESPECIE);
CREATE INDEX PEDIDOS_IDX5 ON PEDIDOS (ID_FORMA);
CREATE INDEX PEDIDOS_IDX6 ON PEDIDOS (ID_VENDEDOR);
CREATE INDEX PEDIDOS_IDX7 ON PEDIDOS (ID_VEICULO);
CREATE INDEX PEDIDOS_IDX8 ON PEDIDOS (CARTAO);
CREATE INDEX PEDIDOS_IDX9 ON PEDIDOS (DESCRICAO);
CREATE UNIQUE INDEX XPKPEDIDOS ON PEDIDOS (ID_PEDIDO);


/******************************************************************************/
/***                                Triggers                                ***/
/******************************************************************************/


SET TERM ^ ;



/******************************************************************************/
/***                          Triggers for tables                           ***/
/******************************************************************************/



/* Trigger: DEL_PEDIDO */
CREATE OR ALTER TRIGGER DEL_PEDIDO FOR PEDIDOS
ACTIVE BEFORE DELETE POSITION 0
AS
begin
  DELETE FROM pedido_itens WHERE ID_PEDIDO = old.ID_PEDIDO;
  DELETE FROM pedido_itens_log WHERE ID_PEDIDO = old.ID_PEDIDO;
  DELETE FROM pedidos_docs WHERE ID_PEDIDO = old.ID_PEDIDO;
end
^


SET TERM ; ^



/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/
