/******************************************************************************/
/***               Generated by IBExpert 13/04/2023 17:12:21                ***/
/******************************************************************************/

/******************************************************************************/
/***      Following SET SQL DIALECT is just for the Database Comparer       ***/
/******************************************************************************/
SET SQL DIALECT 3;



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/



CREATE TABLE REQUISICOES (
    ID_REQUISICAO     INTEGER NOT NULL,
    ES                SMALLINT,
    ID_CLIENTE        INTEGER,
    DATA_EMISSAO      DATE,
    HORA_EMISSAO      TIME,
    NUMERO            INTEGER,
    ID_FUNCIONARIO    INTEGER,
    PEDIDO            VARCHAR(18),
    OBS               BLOB SUB_TYPE 1 SEGMENT SIZE 80,
    VALOR_REQUISICAO  MOEDA /* MOEDA = DECIMAL(15,2) */,
    ID_VEICULO        INTEGER,
    ID_DEPTO          INTEGER,
    COTACAO           SMALLINT,
    STATUS            SMALLINT,
    VEICULO           VARCHAR(50),
    PLACA             VARCHAR(8),
    ITENS             FLOAT,
    ENTREGUE          FLOAT
);




/******************************************************************************/
/***                              Primary Keys                              ***/
/******************************************************************************/

ALTER TABLE REQUISICOES ADD PRIMARY KEY (ID_REQUISICAO);


/******************************************************************************/
/***                                Indices                                 ***/
/******************************************************************************/

CREATE UNIQUE INDEX XPKREQUISICOES ON REQUISICOES (ID_REQUISICAO);


/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/
